Objective

Import & Settings

Paths

Load Raw Data

Initial Validation

Filter to New Brunswick + Employment + Total Gender

Select Occupation Level

Export Processed Dataset (Parquet + CSV sample)

Data Dictionary Notes

In [1]:
import os
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parents[0] if (Path.cwd().name == "notebooks") else Path.cwd()
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_INTERIM = PROJECT_ROOT / "data" / "interim"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

for p in [DATA_RAW, DATA_INTERIM, DATA_PROCESSED]:
    p.mkdir(parents=True, exist_ok=True)

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 140)

In [2]:
RAW_FILE = DATA_RAW / "statcan_14-10-0416-01_full.csv"

print("Raw dataset path:")
print(RAW_FILE)

Raw dataset path:
c:\Users\edhps\OneDrive\capstone-nb-job-trends\data\raw\statcan_14-10-0416-01_full.csv

In [3]:
# Read a small sample to inspect the dataset structure
sample = pd.read_csv(RAW_FILE, nrows=2000)

print("Shape:", sample.shape)

print("\nColumns:")
print(sample.columns.tolist())

sample.head()

Shape: (2000, 17)

Columns:
['REF_DATE', 'GEO', 'DGUID', 'Labour force characteristics', 'National Occupational Classification (NOC)', 'Gender', 'UOM', 'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS']

,REF_DATE,GEO,DGUID,Labour force characteristics,National Occupational Classification (NOC),Gender,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1987,Canada,2021A000011124,Labour force,"Total, all occupations [00-95]",Total - Gender,Persons in thousands,428,units,0,v1481389670,1.1.1.1,13526.0,NaN,NaN,NaN,1
1,1987,Canada,2021A000011124,Labour force,"Total, all occupations [00-95]",Men+,Persons in thousands,428,units,0,v1481389671,1.1.1.2,7680.2,NaN,NaN,NaN,1
2,1987,Canada,2021A000011124,Labour force,"Total, all occupations [00-95]",Women+,Persons in thousands,428,units,0,v1481389672,1.1.1.3,5845.8,NaN,NaN,NaN,1
3,1987,Canada,2021A000011124,Labour force,"Management occupations [00, 10, 20, 30, 40, 50...",Total - Gender,Persons in thousands,428,units,0,v1481389673,1.1.2.1,1374.4,NaN,NaN,NaN,1
4,1987,Canada,2021A000011124,Labour force,"Management occupations [00, 10, 20, 30, 40, 50...",Men+,Persons in thousands,428,units,0,v1481389674,1.1.2.2,990.7,NaN,NaN,NaN,1

In [4]:
# Select only relevant columns to reduce memory usage
cols = [
    "REF_DATE",
    "GEO",
    "Labour force characteristics",
    "National Occupational Classification (NOC)",
    "Gender",
    "VALUE"
]

df = pd.read_csv(RAW_FILE, usecols=cols)

print("Full dataset shape:", df.shape)

df.head()

Full dataset shape: (534105, 6)

   REF_DATE     GEO Labour force characteristics         National Occupational Classification (NOC)          Gender    VALUE
0      1987  Canada                 Labour force                     Total, all occupations [00-95]  Total - Gender  13526.0
1      1987  Canada                 Labour force                     Total, all occupations [00-95]            Men+   7680.2
2      1987  Canada                 Labour force                     Total, all occupations [00-95]          Women+   5845.8
3      1987  Canada                 Labour force  Management occupations [00, 10, 20, 30, 40, 50...  Total - Gender   1374.4
4      1987  Canada                 Labour force  Management occupations [00, 10, 20, 30, 40, 50...            Men+    990.7

In [5]:
# Filter for New Brunswick, Employment and Total Gender

df_nb = df[
    (df["GEO"] == "New Brunswick") &
    (df["Labour force characteristics"] == "Employment") &
    (df["Gender"] == "Total - Gender")
]

print("Filtered dataset shape:", df_nb.shape)

df_nb.head()

Filtered dataset shape: (2301, 6)

      REF_DATE            GEO Labour force characteristics         National Occupational Classification (NOC)          Gender  VALUE
5160      1987  New Brunswick                   Employment                     Total, all occupations [00-95]  Total - Gender  280.3
5163      1987  New Brunswick                   Employment  Management occupations [00, 10, 20, 30, 40, 50...  Total - Gender   22.4
5166      1987  New Brunswick                   Employment  Legislative and senior management occupations [0]  Total - Gender    1.3
5169      1987  New Brunswick                   Employment  Specialized middle management occupations [10,...  Total - Gender    5.6
5172      1987  New Brunswick                   Employment  Middle management occupations in retail and wh...  Total - Gender   10.1